import {useRef,useState} from "react";
import {Alert,Pressable,SafeAreaView,StyleSheet,Text,View,ScrollView} from "react-native";
import * as ImagePicker from "expo-image-picker";
import {CameraView,useCameraPermissions} from "expo-camera";
import {router} from "expo-router";
import {imageToBase64,setPendingImage} from "../lib/image";

export default function Home(){
 const [busy,setBusy]=useState(false),[camera,setCamera]=useState(false);
 const cameraRef=useRef<CameraView>(null);
 const [permission,requestPermission]=useCameraPermissions();
 async function openImage(uri:string){try{setBusy(true);const image=await imageToBase64(uri);setPendingImage(image.base64,image.mimeType);router.push("/study");}catch{Alert.alert("Couldn't read the photo","Try a clearer photo of your notes.");}finally{setBusy(false);}}
 async function library(){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){Alert.alert("Photos permission needed","Allow photo access to choose notes.");return;}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:0.85,allowsEditing:true});if(!r.canceled)await openImage(r.assets[0].uri);}
 async function capture(){try{setBusy(true);const photo=await cameraRef.current?.takePictureAsync({quality:0.85});if(photo?.uri)await openImage(photo.uri);}catch{Alert.alert("Couldn’t capture the page","Try again with the page centered and well lit.");}finally{setBusy(false);setCamera(false);}}
 async function cameraOpen(){if(!permission?.granted){const p=await requestPermission();if(!p.granted)return;}setCamera(true);}
 if(camera)return <View style={s.cameraScreen}><CameraView ref={cameraRef} style={s.cameraView} facing="back"/><View style={s.cameraOverlay}><Pressable style={s.close} onPress={()=>setCamera(false)}><Text style={s.closeText}>×</Text></Pressable><Text style={s.cameraHint}>Line up your notes in the frame</Text><Pressable style={s.capture} onPress={capture}><View style={s.captureRing}/></Pressable></View></View>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>
  <View style={s.header}><View><Text style={s.eyebrow}>SNAPSTUDY</Text><Text style={s.title}>Study smarter.</Text><Text style={s.sub}>One photo. A complete study session.</Text></View><View style={s.logo}><Text style={s.logoText}>S</Text></View></View>
  <View style={s.hero}><View style={s.spark}><Text style={s.sparkText}>✦</Text></View><Text style={s.heroTitle}>Turn notes into practice</Text><Text style={s.heroSub}>SnapStudy reads your handwritten notes and builds a summary, flashcards, quiz and practice test.</Text><View style={s.actions}><Pressable style={s.primary} onPress={cameraOpen} disabled={busy}><Text style={s.primaryText}>📷  Take photo</Text></Pressable><Pressable style={s.secondary} onPress={library} disabled={busy}><Text style={s.secondaryText}>{busy?"Preparing…":"Choose from photos"}</Text></Pressable></View></View>
  <Text style={s.section}>Your study toolkit</Text><View style={s.grid}>
   {[["◉","Flashcards","Flip and recall"],["✓","Smart quiz","Instant score"],["▣","Practice test","Exam mode"],["≡","Summary","Key ideas only"]].map(([i,n,d])=><View style={s.card} key={n}><Text style={s.icon}>{i}</Text><Text style={s.cardTitle}>{n}</Text><Text style={s.cardDesc}>{d}</Text></View>)}
  </View>
  <View style={s.tip}><Text style={s.tipTitle}>Best results</Text><Text style={s.tipText}>Use bright lighting, keep the page flat, and make sure handwriting is readable.</Text></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#070A12"},container:{padding:22,paddingTop:30,paddingBottom:50},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start",marginBottom:30},eyebrow:{color:"#A7A0B8",fontSize:12,fontWeight:"800",letterSpacing:2},title:{color:"#F7F5FF",fontSize:38,fontWeight:"800",letterSpacing:-1.8,marginTop:6},sub:{color:"#AAA6B8",fontSize:14,lineHeight:21,marginTop:8},logo:{width:44,height:44,borderRadius:14,backgroundColor:"#8B5CF6",alignItems:"center",justifyContent:"center"},logoText:{fontSize:20,fontWeight:"900",color:"#fff"},hero:{backgroundColor:"#0F1320",borderWidth:1,borderColor:"#242A3A",borderRadius:26,padding:22,marginBottom:28},spark:{width:54,height:54,borderRadius:17,backgroundColor:"#19142A",alignItems:"center",justifyContent:"center",marginBottom:18},sparkText:{fontSize:25,color:"#A78BFA"},heroTitle:{color:"#F7F5FF",fontSize:24,fontWeight:"800"},heroSub:{color:"#A29CAF",fontSize:14,lineHeight:21,marginTop:7,marginBottom:20},actions:{gap:10},primary:{height:50,borderRadius:14,backgroundColor:"#8B5CF6",alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:15,fontWeight:"800"},secondary:{height:50,borderRadius:14,borderWidth:1,borderColor:"#353047",alignItems:"center",justifyContent:"center"},secondaryText:{color:"#F4F1FF",fontSize:14,fontWeight:"700"},section:{color:"#f0f2f5",fontSize:16,fontWeight:"800",marginBottom:12},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:"48%",minHeight:125,backgroundColor:"#0F1320",borderWidth:1,borderColor:"#242A3A",borderRadius:18,padding:15},icon:{color:"#F4F1FF",fontSize:20,marginBottom:14},cardTitle:{color:"#F4F1FF",fontSize:14,fontWeight:"800"},cardDesc:{color:"#858096",fontSize:12,lineHeight:17,marginTop:5},tip:{marginTop:14,borderRadius:18,padding:17,backgroundColor:"#0B0E17",borderWidth:1,borderColor:"#202536"},tipTitle:{color:"#F4F1FF",fontWeight:"800",fontSize:13},tipText:{color:"#858096",fontSize:12,lineHeight:18,marginTop:5},cameraScreen:{flex:1,backgroundColor:"#000"},cameraView:{flex:1},cameraOverlay:{...StyleSheet.absoluteFillObject,justifyContent:"space-between",alignItems:"center",paddingTop:60,paddingBottom:45},close:{position:"absolute",top:50,left:20,width:44,height:44,borderRadius:22,backgroundColor:"#0008",alignItems:"center",justifyContent:"center"},closeText:{color:"#fff",fontSize:32,lineHeight:36},cameraHint:{color:"#fff",backgroundColor:"#0008",paddingHorizontal:16,paddingVertical:9,borderRadius:20,overflow:"hidden",fontWeight:"700"},capture:{width:76,height:76,borderRadius:38,borderWidth:5,borderColor:"#fff",alignItems:"center",justifyContent:"center"},captureRing:{width:58,height:58,borderRadius:29,backgroundColor:"#fff"}});
