import {useEffect,useMemo,useState} from "react";
import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {router} from "expo-router";
import {useTheme,type ThemeColors} from "../lib/theme";
import {useLanguage} from "../lib/language";

type Session={id:string;topic:string;summary?:string;createdAt:number};
type PlanSettings={examDate:string;dailyGoal:number};
const dateKey=(d:Date)=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(new Date(v+"T12:00:00").getTime())&&dateKey(new Date(v+"T12:00:00"))===v;
export default function Planner(){
 const {colors:c}=useTheme();const {t,language}=useLanguage();const s=styles(c);
 const [examDate,setExamDate]=useState("");const [dailyGoal,setDailyGoal]=useState(30);const [sessions,setSessions]=useState<Session[]>([]);const [dueByDate,setDueByDate]=useState<Record<string,number>>({});const [weakCount,setWeakCount]=useState(0);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{(async()=>{try{const [settingsRaw,sessionsRaw,reviewRaw,weakRaw]=await AsyncStorage.multiGet(["snapstudy:plannerSettings","snapstudy:sessions","snapstudy:reviewSchedule","snapstudy:weakTopics"]);if(settingsRaw[1]){const x=JSON.parse(settingsRaw[1]) as PlanSettings;setExamDate(x.examDate||"");setDailyGoal([15,30,45,60,90].includes(x.dailyGoal)?x.dailyGoal:30);}if(sessionsRaw[1]){const x=JSON.parse(sessionsRaw[1]);setSessions(Array.isArray(x)?x:[]);}if(reviewRaw[1]){const schedule=JSON.parse(reviewRaw[1]);const counts:Record<string,number>={};for(const value of Object.values(schedule) as any[]){const key=dateKey(new Date(value.dueAt||Date.now()));counts[key]=(counts[key]||0)+1;}setDueByDate(counts);}if(weakRaw[1]){const x=JSON.parse(weakRaw[1]);setWeakCount(Array.isArray(x)?x.filter((item:any)=>!item.mastered).length:0);}}catch{}finally{setLoaded(true);}})();},[]);
 const daysLeft=useMemo(()=>{if(!validDate(examDate))return null;const target=new Date(examDate+"T12:00:00");const today=new Date();today.setHours(12,0,0,0);return Math.ceil((target.getTime()-today.getTime())/86400000);},[examDate]);
 const planDays=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);const key=dateKey(d);const session=sessions.length?sessions[i%sessions.length]:null;const due=dueByDate[key]||0;const tasks:string[]=[];if(due>0)tasks.push(due+" · "+t("dueReviewTask"));if(weakCount>0)tasks.push(t("weakReviewTask"));if(session)tasks.push(session.topic);if(!tasks.length)tasks.push(t("scanToStart"));return {key,day:d.toLocaleDateString(language==="sv"?"sv-SE":language==="ar"?"ar":"en-US",{weekday:"short",day:"numeric",month:"short"}),tasks,session};}),[sessions,dueByDate,weakCount,language,t]);
 async function save(){if(examDate&&!validDate(examDate)){Alert.alert(language==="sv"?"Kontrollera datumet":language==="ar"?"تحقق من التاريخ":"Check the date",t("examDateHint"));return;}if(daysLeft!==null&&daysLeft<0){Alert.alert(language==="sv"?"Datumet har passerat":language==="ar"?"التاريخ مضى":"Date has passed",t("examDate"));return;}try{await AsyncStorage.setItem("snapstudy:plannerSettings",JSON.stringify({examDate,dailyGoal}));Alert.alert(t("saved"),t("planSaved"));}catch{Alert.alert(t("couldntSave"),t("saveFailedBody"));}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} showsVerticalScrollIndicator={false}>
  <Pressable onPress={()=>router.back()}><Text style={s.back}>{t("back")}</Text></Pressable><Text style={s.eyebrow}>SNAPSTUDY · PLAN</Text><Text style={s.title}>{t("plannerTitle")}</Text><Text style={s.subtitle}>{t("examPlannerSub")}</Text>
  <View style={s.card}><Text style={s.label}>{t("examDate")}</Text><TextInput value={examDate} onChangeText={setExamDate} placeholder={t("examDateHint")} placeholderTextColor={c.subtle} keyboardType="numbers-and-punctuation" style={s.input}/>{daysLeft!==null&&<Text style={s.countdown}>{daysLeft===0?(language==="sv"?"Provet är idag":language==="ar"?"الاختبار اليوم":"Your exam is today"):daysLeft>0?daysLeft+" "+t("daysLeft"):(language==="sv"?"Datumet har passerat":language==="ar"?"لقد مر الموعد":"The exam date has passed")}</Text>}{!examDate&&<Text style={s.hint}>{t("noExamDate")}</Text>}
   <Text style={[s.label,{marginTop:18}]}>{t("dailyGoal")} · {dailyGoal} {t("minutesUnit")}</Text><View style={s.goals}>{[15,30,45,60,90].map(n=><Pressable key={n} onPress={()=>setDailyGoal(n)} style={[s.goal,dailyGoal===n&&s.goalActive]}><Text style={[s.goalText,dailyGoal===n&&s.goalTextActive]}>{n}</Text></Pressable>)}</View><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>{t("savePlan")}</Text></Pressable>
  </View>
  <View style={s.sectionRow}><Text style={s.section}>{t("planToday")}</Text><Text style={s.small}>{loaded? sessions.length+" "+t("sessions"):"…"}</Text></View>
  {planDays.map((day,i)=><View key={day.key} style={s.dayCard}><View style={s.dayTop}><View style={s.dayNumber}><Text style={s.dayNumberText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.dayName}>{day.day}</Text><Text style={s.dayGoal}>{dailyGoal} {t("minutesUnit")}</Text></View>{i===0&&<Text style={s.today}>{language==="sv"?"IDAG":language==="ar"?"اليوم":"TODAY"}</Text>}</View>{day.tasks.map((task,j)=><View key={task+j} style={s.taskRow}><Text style={s.bullet}>•</Text><Text style={s.task}>{task}</Text></View>)}</View>)}
  {weakCount>0&&<Pressable style={s.secondary} onPress={()=>router.push("/weak-topics")}><Text style={s.secondaryText}>{t("startWeakReview")} · {weakCount}</Text></Pressable>}
  <Pressable style={s.secondary} onPress={()=>router.push("/history")}><Text style={s.secondaryText}>{t("historyTitle")}</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
const styles=(c:ThemeColors)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.bg},container:{padding:22,paddingTop:25,paddingBottom:40},back:{color:c.muted,fontSize:14,fontWeight:"700",marginBottom:22},eyebrow:{color:c.accent,fontSize:10,fontWeight:"900",letterSpacing:1.8},title:{color:c.text,fontSize:29,fontWeight:"900",marginTop:8},subtitle:{color:c.muted,fontSize:13,lineHeight:20,marginTop:8,marginBottom:18},card:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:18,padding:17,marginBottom:22},label:{color:c.text,fontSize:12,fontWeight:"900",marginBottom:8},input:{height:47,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.input,paddingHorizontal:13,color:c.text,fontSize:14},countdown:{color:c.accent,fontSize:12,fontWeight:"900",marginTop:8},hint:{color:c.subtle,fontSize:11,marginTop:8},goals:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:4},goal:{minWidth:48,paddingVertical:11,paddingHorizontal:13,borderRadius:11,borderWidth:1,borderColor:c.border,alignItems:"center"},goalActive:{backgroundColor:c.accentSoft,borderColor:c.accent},goalText:{color:c.muted,fontSize:12,fontWeight:"900"},goalTextActive:{color:c.accent},primary:{backgroundColor:c.accent,borderRadius:13,paddingVertical:14,alignItems:"center",marginTop:18},primaryText:{color:c.onAccent,fontWeight:"900",fontSize:13},sectionRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:10},section:{color:c.text,fontSize:17,fontWeight:"900"},small:{color:c.subtle,fontSize:10},dayCard:{padding:15,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.surface,marginBottom:10},dayTop:{flexDirection:"row",alignItems:"center",gap:11,marginBottom:9},dayNumber:{width:32,height:32,borderRadius:11,backgroundColor:c.accentSoft,alignItems:"center",justifyContent:"center"},dayNumberText:{color:c.accent,fontWeight:"900"},dayName:{color:c.text,fontSize:13,fontWeight:"900"},dayGoal:{color:c.muted,fontSize:10,marginTop:3},today:{color:c.accent,fontSize:9,fontWeight:"900"},taskRow:{flexDirection:"row",gap:8,marginTop:6},bullet:{color:c.accent,fontSize:16},task:{color:c.muted,fontSize:12,lineHeight:18,flex:1},secondary:{padding:13,borderRadius:12,borderWidth:1,borderColor:c.border,alignItems:"center",marginBottom:10},secondaryText:{color:c.text,fontWeight:"800",fontSize:12}});
