import { useEffect,useState } from "react";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import { useLocalSearchParams,router } from "expo-router";
import { analyzeNotes } from "../lib/api";
import type { StudyResult } from "../lib/api";

export default function Study(){
 const {image}=useLocalSearchParams<{image:string}>();
 const [data,setData]=useState<StudyResult|null>(null); const [error,setError]=useState("");
 useEffect(()=>{if(image) analyzeNotes(image).then(setData).catch(e=>setError(e.message));},[image]);
 if(error)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Couldn't analyze notes</Text><Text style={s.error}>{error}</Text><Pressable style={s.button} onPress={()=>router.back()}><Text style={s.buttonText}>Go back</Text></Pressable></View></SafeAreaView>;
 if(!data)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#fff"/><Text style={s.loading}>Reading your notes…</Text><Text style={s.muted}>Building your study session.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.eyebrow}>AI STUDY SESSION</Text><Text style={s.title}>{data.topic}</Text><View style={s.section}><Text style={s.heading}>Summary</Text><Text style={s.body}>{data.summary}</Text></View><Text style={s.heading}>Flashcards</Text>{data.flashcards.map((x,i)=><View style={s.card} key={i}><Text style={s.q}>{x.question}</Text><Text style={s.a}>{x.answer}</Text></View>)}<Text style={s.heading}>Quiz</Text>{data.quiz.map((x,i)=><View style={s.card} key={i}><Text style={s.q}>{i+1}. {x.question}</Text>{x.options.map((o,j)=><Text key={j} style={s.option}>{String.fromCharCode(65+j)}. {o}</Text>)}</View>)}<Text style={s.heading}>Practice test</Text>{data.practiceTest.map((x,i)=><View style={s.card} key={i}><Text style={s.q}>{i+1}. {x.question}</Text><Text style={s.a}>{x.answer}</Text></View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#08090b"},container:{padding:22,paddingTop:28,paddingBottom:50},center:{flex:1,alignItems:"center",justifyContent:"center",padding:30},back:{color:"#9ca3af",fontSize:15,marginBottom:28},eyebrow:{color:"#8d93a1",fontSize:11,fontWeight:"800",letterSpacing:1.8},title:{color:"#f5f7fa",fontSize:32,fontWeight:"800",marginTop:7,marginBottom:24},loading:{color:"#f5f7fa",fontSize:17,fontWeight:"700",marginTop:18},muted:{color:"#777e8c",marginTop:6},error:{color:"#b8bdc8",textAlign:"center",lineHeight:21,marginVertical:15},button:{backgroundColor:"#f4f6f8",paddingHorizontal:22,paddingVertical:13,borderRadius:12},buttonText:{color:"#090a0c",fontWeight:"800"},section:{backgroundColor:"#111318",borderWidth:1,borderColor:"#242831",borderRadius:18,padding:17,marginBottom:26},heading:{color:"#f4f6f8",fontSize:18,fontWeight:"800",marginBottom:10,marginTop:18},body:{color:"#a5aab5",fontSize:14,lineHeight:22},card:{backgroundColor:"#111318",borderWidth:1,borderColor:"#242831",borderRadius:16,padding:16,marginTop:10},q:{color:"#f4f6f8",fontSize:14,fontWeight:"700",lineHeight:21},a:{color:"#a5aab5",fontSize:13,lineHeight:20,marginTop:10},option:{color:"#a5aab5",fontSize:13,lineHeight:21,marginTop:7}});
