import { Pressable, StyleSheet, Text, View } from "react-native";
import { router, usePathname } from "expo-router";

import { useTheme, type ThemeColors } from "../lib/theme";
import { useLanguage } from "../lib/language";
export default function BottomNav(){
 const { colors:c } = useTheme(); const s=makeStyles(c); const {t}=useLanguage();
 const path=usePathname();
 const items=[["/","⌂",t("home")],["/history","▤",t("history")],["/account","◉",t("account")]] as const;
 return <View style={s.wrap}><Pressable style={s.plusBar} onPress={()=>router.push("/plus")}><View style={s.plusMark}><Text style={s.plusMarkText}>✦</Text></View><View style={{flex:1}}><Text style={s.plusTitle}>SnapStudy Plus</Text><Text style={s.plusSub}>More ways to study. More control.</Text></View><Text style={s.plusAction}>Go Plus ↗</Text></Pressable><View style={s.bar}>{items.map(([href,icon,label])=>{const active=path===href;return <Pressable key={href} onPress={()=>router.replace(href)} style={s.item}><View style={[s.icon,active&&s.activeIcon]}><Text style={[s.iconText,active&&s.activeText]}>{icon}</Text></View><Text style={[s.label,active&&s.activeText]}>{label}</Text></Pressable>})}</View></View>
}
const makeStyles = (c: ThemeColors) => StyleSheet.create({wrap:{paddingHorizontal:14,paddingTop:8,paddingBottom:10,backgroundColor:c.bg},plusBar:{minHeight:56,marginBottom:8,paddingHorizontal:12,paddingVertical:9,borderRadius:16,backgroundColor:c.accentSoft,borderWidth:1,borderColor:c.accent,flexDirection:"row",alignItems:"center",gap:10},plusMark:{width:30,height:30,borderRadius:10,backgroundColor:c.surface,alignItems:"center",justifyContent:"center"},plusMarkText:{color:c.accent,fontSize:16,fontWeight:"900"},plusTitle:{color:c.text,fontSize:12,fontWeight:"900"},plusSub:{color:c.muted,fontSize:10,marginTop:2},plusAction:{color:c.accent,fontSize:11,fontWeight:"900"},bar:{height:68,borderRadius:22,backgroundColor:c.surfaceAlt,borderWidth:1,borderColor:c.border,flexDirection:"row",alignItems:"center",justifyContent:"space-around"},item:{flex:1,alignItems:"center",justifyContent:"center",gap:4},icon:{width:38,height:30,borderRadius:11,alignItems:"center",justifyContent:"center"},activeIcon:{backgroundColor:c.accentSoft},iconText:{color:c.subtle,fontSize:18,fontWeight:"900"},activeText:{color:c.accent},label:{color:c.subtle,fontSize:10,fontWeight:"800"}});